plugins {
    id 'fabric-loom' version '1.1-SNAPSHOT'
    id 'maven-publish'
}

repositories {
    mavenCentral()
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
}

extensions {
    loom {
        minecraftVersion = '1.20.4'
        mappings = '1.20.4+build.1'
        modId = 'knifemod'
        version = '1.0.0'
        accessWidener = 'src/main/resources/accessWidener.txt'
    }
}

dependencies {
    minecraft 'com.mojang:minecraft:1.20.4'
    mappings 'net.fabricmc:yarn:1.20.4+build.1:v2'
    modImplementation 'net.fabricmc:fabric-loader:0.14.22'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.83.0+1.20.4'
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'minecraft_version', project.minecraftVersion
    from(sourceSets.main.resources.srcDirs) {
        include 'fabric.mod.json'
        expand 'version':project.version, 'minecraft_version':project.minecraftVersion
    }
    into 'build/resources/main'
}
